### ISSUE TITLE
Should it be \sum_{i < j} a_i a_j \Cov(x_i, x_j)  instead of \sum_{i < j} \Cov(x_i, x_j)  in line 100? 

### ISSUE THREAD

**Issue by jessica131324** [ryantibs/timeseries-f23#3]
https://github.com/ryantibs/timeseries-f23/blob/0182af5ff00ec3b48ad3ff6e31b38b0cc2f542c0/lectures/dependence/dependence.tex#L99C1-L101C16

**Comment by ryantibs** [comment]
Thank you! Fixed now
